'use client'

import * as React from 'react'
import { useWorkspace } from './workspace-provider'
import type { ProposalDocument, ProposalRow, ProposalSection } from '@/proposal-engine'
import { cn } from '@/lib/utils'

/**
 * ProposalPreview — renders the ProposalDocument as ordinary React. The exact
 * same document powers the PDF/Excel/HTML/Email exporters, guaranteeing
 * output consistency across channels.
 */
export function ProposalPreview({ doc: docProp, className }: { doc?: ProposalDocument; className?: string }) {
  const { proposal } = useWorkspace()
  const doc = docProp ?? proposal
  return (
    <article className={cn('space-y-8 rounded-md border border-border bg-card p-6', className)}>
      {doc.sections.map((section) => <SectionView key={section.id} section={section} />)}
      <footer className="mt-8 border-t border-border pt-3 text-center text-[10px] text-muted-foreground">
        {doc.branding.footerText || `Generated by ${doc.branding.companyName}`} · Proposal Engine {doc.meta.proposalEngineVersion}
      </footer>
    </article>
  )
}

function SectionView({ section }: { section: ProposalSection }) {
  return (
    <section id={section.id} className={cn(section.kind === 'cover' && 'text-center')}>
      {section.rows.map((row, i) => <RowView key={`${section.id}-${i}`} row={row} />)}
    </section>
  )
}

function RowView({ row }: { row: ProposalRow }) {
  switch (row.kind) {
    case 'heading': {
      const level = row.level ?? 1
      const cls = level === 1 ? 'text-2xl font-bold' : level === 2 ? 'mt-4 text-lg font-semibold' : 'mt-3 text-sm font-semibold uppercase tracking-wider text-muted-foreground'
      const Tag = (level === 1 ? 'h1' : level === 2 ? 'h2' : 'h3') as keyof React.JSX.IntrinsicElements
      return <Tag className={cls}>{row.text}</Tag>
    }
    case 'paragraph':
      return <p className="mt-2 text-sm text-foreground/90">{row.text}</p>
    case 'key_value':
      return (
        <dl className="mt-3 grid grid-cols-[1fr_1.5fr] gap-x-4 gap-y-1 text-sm">
          {row.items.map((it, idx) => (
            <React.Fragment key={idx}>
              <dt className="text-muted-foreground">{it.label}</dt>
              <dd className="font-medium text-foreground">{it.value}</dd>
            </React.Fragment>
          ))}
        </dl>
      )
    case 'table':
      return (
        <div className="mt-3 overflow-hidden rounded-md border border-border">
          <table className="w-full border-collapse text-xs">
            <thead className="bg-muted/40 text-left">
              <tr>
                {row.columns.map((c, i) => <th key={i} className="px-2 py-1.5 font-semibold text-muted-foreground">{c}</th>)}
              </tr>
            </thead>
            <tbody>
              {row.rows.map((r, i) => (
                <tr key={i} className="border-t border-border">
                  {r.map((cell, j) => <td key={j} className="px-2 py-1.5 align-top">{cell}</td>)}
                </tr>
              ))}
            </tbody>
            {row.summary && (
              <tfoot className="bg-muted/20">
                {row.summary.map((s, i) => (
                  <tr key={i} className="border-t border-border">
                    <td colSpan={row.columns.length - 1} className="px-2 py-1.5 text-right text-muted-foreground">{s.label}</td>
                    <td className="px-2 py-1.5 text-right font-mono font-semibold">{s.value}</td>
                  </tr>
                ))}
              </tfoot>
            )}
          </table>
        </div>
      )
    case 'bullets':
      return (
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
          {row.items.map((i, idx) => <li key={idx}>{i}</li>)}
        </ul>
      )
    case 'callout': {
      const tone = row.tone === 'critical' ? 'border-destructive/40 bg-destructive/5 text-destructive'
        : row.tone === 'warning' ? 'border-amber-500/30 bg-amber-500/5 text-amber-800 dark:text-amber-200'
        : row.tone === 'success' ? 'border-emerald-500/30 bg-emerald-500/5 text-emerald-700 dark:text-emerald-300'
        : 'border-blue-500/30 bg-blue-500/5 text-blue-800 dark:text-blue-200'
      return (
        <div className={cn('mt-2 rounded-md border p-2 text-xs', tone)}>
          {row.title && <div className="mb-0.5 text-[10px] font-bold uppercase tracking-wider">{row.title}</div>}
          <div>{row.text}</div>
        </div>
      )
    }
  }
}
