'use client'

import * as React from 'react'
import {
  Document, Page, Text, View, StyleSheet, Font, pdf,
} from '@react-pdf/renderer'
import type { ProposalDocument, ProposalRow, ProposalSection, ProposalBranding } from '@/proposal-engine'

export const PDF_ENGINE_VERSION = '0.5.0'

// Register web-safe fonts. @react-pdf ships with Helvetica by default; adding
// bold + italic families gives us the professional typography Release 0.5
// requires. All URLs are CDN-served open-source fonts.
try {
  Font.register({
    family: 'Inter',
    fonts: [
      { src: 'https://cdn.jsdelivr.net/npm/@fontsource/inter@5.0.16/files/inter-latin-400-normal.woff', fontWeight: 400 },
      { src: 'https://cdn.jsdelivr.net/npm/@fontsource/inter@5.0.16/files/inter-latin-600-normal.woff', fontWeight: 600 },
      { src: 'https://cdn.jsdelivr.net/npm/@fontsource/inter@5.0.16/files/inter-latin-700-normal.woff', fontWeight: 700 },
    ],
  })
} catch { /* Font already registered or environment doesn't support it. */ }

function sheet(branding: ProposalBranding) {
  const primary = branding.primaryColor || '#0F172A'
  const accent = branding.accentColor || '#0EA5E9'
  return StyleSheet.create({
    page: {
      paddingTop: 56, paddingBottom: 56, paddingHorizontal: 48,
      fontSize: 10, fontFamily: 'Helvetica', color: '#0F172A', lineHeight: 1.45,
    },
    header: {
      position: 'absolute', top: 24, left: 48, right: 48,
      flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
      borderBottomWidth: 1, borderBottomColor: '#E5E7EB', paddingBottom: 6,
    },
    footer: {
      position: 'absolute', bottom: 24, left: 48, right: 48,
      flexDirection: 'row', justifyContent: 'space-between',
      fontSize: 8, color: '#64748B',
      borderTopWidth: 1, borderTopColor: '#E5E7EB', paddingTop: 6,
    },
    h1: { fontSize: 26, fontWeight: 700, color: primary, marginBottom: 8 },
    h2: { fontSize: 14, fontWeight: 700, color: primary, marginTop: 14, marginBottom: 4 },
    h3: { fontSize: 10, fontWeight: 700, color: accent, marginTop: 10, marginBottom: 2, textTransform: 'uppercase', letterSpacing: 0.6 },
    para: { marginTop: 2, marginBottom: 2 },
    kvRow: { flexDirection: 'row', marginBottom: 1 },
    kvKey: { width: '35%', color: '#475569' },
    kvVal: { width: '65%', fontWeight: 700 },
    table: { marginTop: 6, marginBottom: 6, borderWidth: 1, borderColor: '#E5E7EB' },
    tRowHead: { flexDirection: 'row', backgroundColor: '#F1F5F9' },
    tRow:     { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#E5E7EB' },
    tCell:    { paddingVertical: 4, paddingHorizontal: 5, fontSize: 9 },
    tCellB:   { paddingVertical: 4, paddingHorizontal: 5, fontSize: 9, fontWeight: 700 },
    tSummary: { flexDirection: 'row', backgroundColor: '#F8FAFC', borderTopWidth: 1, borderTopColor: '#E5E7EB' },
    bullet: { flexDirection: 'row', marginBottom: 1 },
    calloutBox: { padding: 6, marginTop: 4, marginBottom: 4, borderWidth: 1, borderRadius: 3 },
    coverBox: { marginTop: 100, alignItems: 'center', textAlign: 'center' },
    coverBrand: { fontSize: 34, fontWeight: 700, color: primary },
    coverTag:   { fontSize: 11, color: '#64748B', marginTop: 4 },
    coverProject: { fontSize: 20, fontWeight: 700, marginTop: 40, color: primary },
  })
}

function Header({ doc, s }: { doc: ProposalDocument; s: ReturnType<typeof sheet> }) {
  return (
    <View style={s.header} fixed>
      <Text style={{ fontWeight: 700 }}>{doc.branding.companyName}</Text>
      <Text>{doc.project.projectName} · {doc.project.proposalNumber} · Rev {doc.project.revision}</Text>
    </View>
  )
}

function Footer({ doc, s }: { doc: ProposalDocument; s: ReturnType<typeof sheet> }) {
  return (
    <View style={s.footer} fixed>
      <Text>{doc.branding.footerText || `Generated by ${doc.branding.companyName}`}</Text>
      <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  )
}

function Row({ row, s }: { row: ProposalRow; s: ReturnType<typeof sheet> }) {
  switch (row.kind) {
    case 'heading': {
      const style = row.level === 1 ? s.h1 : row.level === 2 ? s.h2 : s.h3
      return <Text style={style}>{row.text}</Text>
    }
    case 'paragraph':
      return <Text style={s.para}>{row.text}</Text>
    case 'key_value':
      return (
        <View style={{ marginTop: 3, marginBottom: 3 }} wrap={false}>
          {row.items.map((it, i) => (
            <View key={i} style={s.kvRow}>
              <Text style={s.kvKey}>{it.label}</Text>
              <Text style={s.kvVal}>{it.value}</Text>
            </View>
          ))}
        </View>
      )
    case 'table': {
      const colWidth = 100 / row.columns.length
      return (
        <View style={s.table}>
          <View style={s.tRowHead}>
            {row.columns.map((c, i) => (
              <Text key={i} style={[s.tCellB, { width: `${colWidth}%`, textAlign: i === 0 ? 'left' : 'right' }]}>{c}</Text>
            ))}
          </View>
          {row.rows.map((r, i) => (
            <View key={i} style={s.tRow} wrap={false}>
              {r.map((cell, j) => (
                <Text key={j} style={[s.tCell, { width: `${colWidth}%`, textAlign: j === 0 ? 'left' : 'right' }]}>{cell}</Text>
              ))}
            </View>
          ))}
          {row.summary?.map((sm, i) => (
            <View key={i} style={s.tSummary} wrap={false}>
              <Text style={[s.tCell, { width: `${100 - colWidth}%`, textAlign: 'right', color: '#475569' }]}>{sm.label}</Text>
              <Text style={[s.tCellB, { width: `${colWidth}%`, textAlign: 'right' }]}>{sm.value}</Text>
            </View>
          ))}
        </View>
      )
    }
    case 'bullets':
      return (
        <View style={{ marginTop: 3 }}>
          {row.items.map((i, idx) => (
            <View key={idx} style={s.bullet}><Text>• </Text><Text>{i}</Text></View>
          ))}
        </View>
      )
    case 'callout': {
      const bg = row.tone === 'critical' ? '#FEE2E2' : row.tone === 'warning' ? '#FEF3C7' : row.tone === 'success' ? '#D1FAE5' : '#DBEAFE'
      const bd = row.tone === 'critical' ? '#DC2626' : row.tone === 'warning' ? '#D97706' : row.tone === 'success' ? '#059669' : '#2563EB'
      return (
        <View style={[s.calloutBox, { backgroundColor: bg, borderColor: bd }]} wrap={false}>
          {row.title && <Text style={{ fontWeight: 700, marginBottom: 2 }}>{row.title}</Text>}
          <Text>{row.text}</Text>
        </View>
      )
    }
  }
}

function SectionView({ section, s }: { section: ProposalSection; s: ReturnType<typeof sheet> }) {
  if (section.kind === 'cover') {
    // Special-case rendering for the cover page.
    const brandRow = section.rows.find(r => r.kind === 'heading' && r.text)
    const projectRow = section.rows.find(r => r.kind === 'heading' && r.level === 2)
    const tagRow = section.rows.find(r => r.kind === 'paragraph')
    const kv = section.rows.find(r => r.kind === 'key_value')
    return (
      <View style={s.coverBox}>
        <Text style={s.coverBrand}>{brandRow?.kind === 'heading' ? brandRow.text : ''}</Text>
        {tagRow?.kind === 'paragraph' && <Text style={s.coverTag}>{tagRow.text}</Text>}
        <Text style={s.coverProject}>{projectRow?.kind === 'heading' ? projectRow.text : ''}</Text>
        {kv?.kind === 'key_value' && (
          <View style={{ marginTop: 40, width: 400 }}>
            {kv.items.map((it, i) => (
              <View key={i} style={s.kvRow}><Text style={s.kvKey}>{it.label}</Text><Text style={s.kvVal}>{it.value}</Text></View>
            ))}
          </View>
        )}
      </View>
    )
  }
  return <View>{section.rows.map((r, i) => <Row key={i} row={r} s={s} />)}</View>
}

export function ProposalPdfDocument({ doc }: { doc: ProposalDocument }) {
  const s = sheet(doc.branding)
  return (
    <Document title={doc.title} author={doc.branding.companyName} subject={`Proposal ${doc.project.proposalNumber ?? ''}`}>
      {/* Cover page: full page, no header */}
      <Page size="A4" style={s.page}>
        <SectionView section={doc.sections[0]} s={s} />
        <Footer doc={doc} s={s} />
      </Page>
      {/* Content pages */}
      {doc.sections.slice(1).map((sec) => (
        <Page key={sec.id} size="A4" style={s.page}>
          <Header doc={doc} s={s} />
          <SectionView section={sec} s={s} />
          <Footer doc={doc} s={s} />
        </Page>
      ))}
    </Document>
  )
}

/**
 * Render a ProposalDocument into a Blob. Callers usually pipe this into a
 * download stream via `file-saver`.
 */
export async function renderProposalPdfBlob(doc: ProposalDocument): Promise<Blob> {
  const instance = pdf(<ProposalPdfDocument doc={doc} />)
  return await instance.toBlob()
}
